### ISSUE TITLE
等一个代码更新！

### ISSUE THREAD

**Issue by nmbtwzt** [NicholasCao/BeautifulPrompt#1]
感谢大佬开源了beautifulprompt模型，并提供了Demo，这对我来说是个极大的激励。
我对这个方面有着浓厚的兴趣，并且希望有机会更深入地学习和理解这个模型。如果可能的话，我也非常期待您能尽快公布源代码，这使得我可以自己研究学习，并尝试训练和调试。
再次感谢您的开源精神和对社区的贡献。

**Comment by NicholasCao** [comment]
需要等待论文接收和公司开源流程通过😂。敬请期待

**Comment by nmbtwzt** [comment]
明白了，非常感谢。希望可以早日看到论文和代码！
